#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# admin:
#     path: /admin/
#     controller: App\Controller\AdminController::index

# admin_login:
#     path: /admin_login/
#     controller: App\Controller\AdminSecurityController::index